### ISSUE TITLE
Error resolving url (downloadSingleTrack)

### ISSUE THREAD

**Issue by kahekahe** [mrwnwttk/scdl#10]
I've been using this for a while, and it's been working well.

Just run into the following error though. Any ideas on what's going wrong?

I'm using latest version.

```python
(venv_std) pi@rpi4:~/Downloads/scdl $ scdl -p
Premium flag set!
Please enter a URL: https://soundcloud.com/hollick_nobaddays/no-bad-days-with-gabriel-szatan-december-2019
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 550, in <module>
    main()
  File "/usr/local/bin/scdl", line 47, in main
    downloadSingleTrack(soundcloudUrl, 1, 0)
  File "/usr/local/bin/scdl", line 106, in downloadSingleTrack
    trackId = getTrackId(soundcloudUrl)
  File "/usr/local/bin/scdl", line 248, in getTrackId
    trackId = json.loads(s)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by mrwnwttk** [comment]
Update to the latest version. There was a (seemingly) server-side bug which returned an empty json file when attempting to make a request. It now loops until it gets a valid file, which should fix that. It runs just fine on the newest version on my machine.

**Comment by mrwnwttk** [comment]
You say that you're running the latest version but you're not. Line 106 is something entirely different. Please re-download and re-install. There was a (seemingly) server side bug which returned an empty json file despite the request being valid. I fixed that by just continuously making requests until SC returns a valid file. It runs just fine on the lastest version on my machine.

**Comment by kahekahe** [comment]
apologies, i had pulled, but forgot to `cp "$installerPath"/scdl /usr/local/bin/scdl`
