### ISSUE TITLE
CoverArt 404 issue

### ISSUE THREAD

**Issue by vaseimieum** [mrwnwttk/scdl#15]
When downloading a single track or in a playlist (doesn't matter) the script will stop continuing if there is no accompanying cover art with the track. I also tried using the -dd & -m flags and the same error is still produced even when the -dd flag is set on its own. When downloading a playlist with the no cover art track, it will stop and not continue on to the next tracks in line.

Single track: https://soundcloud.com/perturbator/perturbator-disco-girls?in=evanthewriter/sets/nostalgia-nights-198x
In this playlist track #214: https://soundcloud.com/evanthewriter/sets/nostalgia-nights-198x

scdl always stops at #214 in this particular playlist and doesn't continue on.

### Terminal output for the single track -p:
scdl -p -dd -m
Description disabled!
Premium flag set!
Metadata flag set!
Please enter a URL: https://soundcloud.com/perturbator/perturbator-disco-girls?in=evanthewriter/sets/nostalgia-nights-198x
File '47246080.m4a' already exists. Overwrite ? [y/N] y
File '47246080.mp3' already exists. Overwrite ? [y/N] y
Writing metadata to file:  Perturbator - Disco Girls_47246080_metadata.json
trackName: Perturbator - Disco Girls
artist: PERTURBATOR
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 721, in <module>
    main()
  File "/usr/local/bin/scdl", line 54, in main
    downloadSingleTrack(soundcloudUrl, "", 1, 0)
  File "/usr/local/bin/scdl", line 182, in downloadSingleTrack
    trackName, artist, coverFlag = getTags(soundcloudUrl)
  File "/usr/local/bin/scdl", line 482, in getTags
    urllib.request.urlretrieve(cover, "cover.jpg")
  File "/usr/lib/python3.6/urllib/request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found`

**Comment by mrwnwttk** [comment]
Sorry for the late response, I was busy with exams. The issue here is that while there is no cover visible (which in 99% of cases means that it's not set), the URL for the cover is set to https://i1.sndcdn.com/artworks-000023781337-hoixi4-large.jpg, which isn't empty. It's not a photo, instead it just shows the message "cannot find original", which the script doesn't know how to handle (because it's neither nothing nor an image). I'll try to fix this.

**Comment by mrwnwttk** [comment]
Fixed. It should now also set the cover art to the artist's profile picture if the original cover art somehow got lost. Let me know if the issue still occurs on your end.
