### ISSUE TITLE
CLI option for path to ffmpeg

### ISSUE THREAD

**Issue by sam-cross** [mrwnwttk/scdl#16]
Would be useful if ffmpeg isn't on PATH

**Comment by mrwnwttk** [comment]
Won't implement that. As soon as there are spaces in the path I'd have to write my own parser for the arguments instead of just sticking with argparse. Adding FFMPEG to PATH isn't that hard.

**Comment by sam-cross** [comment]
youtube-dl has this option. You can put paths in quotation marks (this is required by almost every CLI tool anyway). argparse would support it, and [people have done it](https://stackoverflow.com/questions/38834378/path-to-a-directory-as-argparse-argument).

I can submit a PR with this feature.
