### ISSUE TITLE
It gives me error when trying to download

### ISSUE THREAD

**Issue by Aij75** [mrwnwttk/scdl#19]
PS C:\Users\KAVOSH\Desktop\scdl-master> python scdl -p
Premium flag set!
Please enter a URL: https://soundcloud.com/cleopatra-recs/eye-of-the-tiger
trackName: Eye Of The Tiger
artist: Cleopatra Records
Traceback (most recent call last):
  File "scdl", line 766, in <module>
    main()
  File "scdl", line 56, in main
    downloadSingleTrack(soundcloudUrl, "", 1, 0)
  File "scdl", line 196, in downloadSingleTrack
    renameFile(trackId, trackName, 0)
  File "scdl", line 263, in renameFile
    os.rename(oldFilename, newFilename)
FileNotFoundError: [WinError 2] The system cannot find the file specified: '73115584.mp3' -> 'Eye Of The Tiger.mp3'

**Comment by mrwnwttk** [comment]
Are you sure you installed FFMPEG correctly?

**Comment by Aij75** [comment]
> Are you sure you installed FFMPEG correctly?

Thanks for reply.

I just download FFMPEG and unzip it. Then paste it to my scdl folder. And then add FFMPEG folder to my system PATH. does it mean installing? or i missing something.?

**Comment by mrwnwttk** [comment]
A quick google search for "Add ffmpeg to PATH" will do the trick. I would just make a folder called "ffmpeg" in your Documents folder and add that one to the PATH environment variable. It's not that hard.
