### ISSUE TITLE
Could this be merged with youtube-dl

### ISSUE THREAD

**Issue by Zipdox** [mrwnwttk/scdl#24]
Could you turn this into a youtube-dl extractor and send a pull request to https://github.com/ytdl-org/youtube-dl/ ? That would be really appreciated.

**Comment by mrwnwttk** [comment]
No, for multiple reasons. First of all, that seems like a ton of work which I do not have the time for and even if I did, this isn't exactly the most legal tool because of the whole premium account thing, which youtube-dl doesn't want anything to do with. Not gonna happen.
