### ISSUE TITLE
AttributeError: 'module' object has no attribute '_create_unverified_context'

### ISSUE THREAD

**Issue by kahekahe** [mrwnwttk/scdl#4]
Hi, this looks promising - but I'm getting an error when I run the latest version:

```
Traceback (most recent call last):

  File "/usr/local/bin/scdl", line 30, in <module>

​    ssl._create_default_https_context = ssl._create_unverified_context

AttributeError: 'module' object has no attribute '_create_unverified_context'
```

**Comment by mrwnwttk** [comment]
What python version are you using?

**Comment by kahekahe** [comment]
Python 3.4.2

**Comment by mrwnwttk** [comment]
Please update python3. Support for _create_unverified_context was added in 3.6 if I'm not mistaken. Let me know if that solves the problem.

**Comment by kahekahe** [comment]
Ok. I was trying to use on raspberry pi which only has 3.4.2. Nevermind.

**Comment by mrwnwttk** [comment]
You can still update, see for example here: https://medium.com/@isma3il/install-python-3-6-or-3-7-and-pip-on-raspberry-pi-85e657aadb1e

**Comment by kahekahe** [comment]
Thanks, I have it working now (just run into another issue with playlists - but will open separate issue)
