### ISSUE TITLE
private links dont download

### ISSUE THREAD

**Issue by jonestly** [mrwnwttk/scdl#7]
it gives me this error with the premium flag set.

![image](https://user-images.githubusercontent.com/53351681/66960981-a5fbf380-f03b-11e9-8cc5-31294d2d1175.png)

**Comment by mrwnwttk** [comment]
Resolving private links doesn't work the way resolving public links does. I'll look into it.

**Comment by mrwnwttk** [comment]
Private links (with M4A files available) are working now. I'll get to regular MP3 files over the next couple of days :)

**Comment by jonestly** [comment]
thank you for your repl(ies)y, but i still get this error with the updated script. 
![image](https://user-images.githubusercontent.com/53351681/67819123-3b5ea500-fa8a-11e9-9c63-21f855b4c308.png)

**Comment by mrwnwttk** [comment]
You're not running the latest version. Line 126 doesn't match.

**Comment by mrwnwttk** [comment]
Both regular as well as premium private links are now working.
