### ISSUE TITLE
some links wil not generate an m4a file.

### ISSUE THREAD

**Issue by jonestly** [mrwnwttk/scdl#8]
as an example:

![image](https://user-images.githubusercontent.com/53351681/66961226-27538600-f03c-11e9-9e48-55f3f12219de.png)

it outputs it as an mp3 file instead. i am on windows.

**Comment by mrwnwttk** [comment]
That is normal behavior. Some tracks were never uploaded as a 320kbps MP3 or anything past 128kbps MP3. In that case, only the MP3 is available because it wasn't worth transcoding.
